// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlPS3xzjjVcI0I4gpxRAR-z7R06IHqrpU',
    appId: '1:355474684455:web:e111a67058fa47f887ec02',
    messagingSenderId: '355474684455',
    projectId: 'ecommerce-829bb',
    authDomain: 'ecommerce-829bb.firebaseapp.com',
    storageBucket: 'ecommerce-829bb.appspot.com',
    measurementId: 'G-FKD4FV9GPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLCHcUQOJLMzIdIVcRNkIFT0OXlxtsP8',
    appId: '1:355474684455:android:78b55ea1e32f4e1f87ec02',
    messagingSenderId: '355474684455',
    projectId: 'ecommerce-829bb',
    storageBucket: 'ecommerce-829bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9hk6A3mXiiPJA2Ei44snf989o9HKfvRw',
    appId: '1:355474684455:ios:6c3c924fc82a2bc887ec02',
    messagingSenderId: '355474684455',
    projectId: 'ecommerce-829bb',
    storageBucket: 'ecommerce-829bb.appspot.com',
    iosClientId: '355474684455-8pe0b7c2hjrrl8h18761m6v2rmrtrdfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.eccommerce2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9hk6A3mXiiPJA2Ei44snf989o9HKfvRw',
    appId: '1:355474684455:ios:6c3c924fc82a2bc887ec02',
    messagingSenderId: '355474684455',
    projectId: 'ecommerce-829bb',
    storageBucket: 'ecommerce-829bb.appspot.com',
    iosClientId: '355474684455-8pe0b7c2hjrrl8h18761m6v2rmrtrdfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.eccommerce2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8TvxiYidU6rBdKoRYz2wbQkFMK5ZdS4E',
    appId: '1:355474684455:web:d49bc2f44ad44c1687ec02',
    messagingSenderId: '355474684455',
    projectId: 'ecommerce-829bb',
    authDomain: 'ecommerce-829bb.firebaseapp.com',
    storageBucket: 'ecommerce-829bb.appspot.com',
    measurementId: 'G-MXKMGGEH3H',
  );

}